apiVersion: v1
kind: Service
metadata:
  name: client-api
  namespace: spire
spec:
  type: NodePort
  ports:
  - name: grpc
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: client-api
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: client-api
  namespace: spire
  labels:
    app: client-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-api
  serviceName: client-api
  template:
    metadata:
      labels:
        app: client-api
    spec:
      nodeName: minikube-m02
      containers:
      - name: client-api
        image: localhost:5000/stellaris-client:latest
        volumeMounts:
        - name: spire-bundle
          mountPath: /run/spire/bundle
        - name: spire-agent-socket
          mountPath: /run/spire/sockets
          readOnly: true
      volumes:
      - name: spire-bundle
        configMap:
          name: spire-bundle
      - name: spire-agent-socket
        hostPath:
          path: /run/spire/sockets
          type: DirectoryOrCreate

