apiVersion: v1
kind: Service
metadata:
  name: stellaris-api
  namespace: spire
spec:
  type: NodePort
  ports:
    - name: grpc
      port: 8090
      targetPort: 8090
      protocol: TCP
  selector:
    app: stellaris-api
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stellaris-api
  namespace: spire
  labels:
    app: stellaris-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stellaris-api
  serviceName: stellaris-api
  template:
    metadata:
      labels:
        app: stellaris-api
    spec:
      nodeName: minikube-m03
      containers:
        - name: stellaris-api
          image: localhost:5000/stellaris-api:latest
          volumeMounts:
            - name: spire-bundle
              mountPath: /run/spire/bundle
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
              readOnly: false
      volumes:
        - name: spire-bundle
          configMap:
            name: spire-bundle
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: DirectoryOrCreate
      
